# Generated by Django 4.2.28 on 2026-05-12 21:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hosts', '0013_alter_hostrepo_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplianceProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_id', models.CharField(max_length=255, unique=True)),
                ('title', models.CharField(blank=True, default='', max_length=512)),
                ('description', models.TextField(blank=True, default='')),
            ],
            options={
                'ordering': ['profile_id'],
            },
        ),
        migrations.CreateModel(
            name='ComplianceRule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_id', models.CharField(max_length=255, unique=True)),
                ('title', models.CharField(blank=True, default='', max_length=512)),
                ('severity', models.CharField(blank=True, default='', max_length=32)),
                ('description', models.TextField(blank=True, default='')),
            ],
            options={
                'ordering': ['rule_id'],
            },
        ),
        migrations.CreateModel(
            name='ComplianceScan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datastream', models.CharField(blank=True, default='', max_length=255)),
                ('score', models.FloatField(default=0.0)),
                ('score_maximum', models.FloatField(default=100.0)),
                ('pass_count', models.IntegerField(default=0)),
                ('fail_count', models.IntegerField(default=0)),
                ('error_count', models.IntegerField(default=0)),
                ('notapplicable_count', models.IntegerField(default=0)),
                ('scanned_at', models.DateTimeField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compliance_scans', to='hosts.host')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scans', to='compliance.complianceprofile')),
            ],
            options={
                'ordering': ['-scanned_at'],
            },
        ),
        migrations.CreateModel(
            name='ComplianceResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.CharField(choices=[('pass', 'Pass'), ('fail', 'Fail'), ('error', 'Error'), ('notapplicable', 'Not Applicable'), ('notchecked', 'Not Checked'), ('notselected', 'Not Selected'), ('informational', 'Informational'), ('fixed', 'Fixed')], max_length=32)),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='compliance.compliancerule')),
                ('scan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='compliance.compliancescan')),
            ],
        ),
        migrations.AddConstraint(
            model_name='compliancescan',
            constraint=models.UniqueConstraint(fields=('host', 'profile', 'scanned_at'), name='unique_compliance_scan'),
        ),
        migrations.AddIndex(
            model_name='complianceresult',
            index=models.Index(fields=['rule', 'result'], name='compliance__rule_id_3f1e07_idx'),
        ),
        migrations.AddConstraint(
            model_name='complianceresult',
            constraint=models.UniqueConstraint(fields=('scan', 'rule'), name='unique_compliance_result'),
        ),
    ]
