# Generated by Django 4.2.28 on 2026-05-12 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0005_alter_report_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='report',
            options={'ordering': ['-created'], 'verbose_name': 'Report', 'verbose_name_plural': 'Reports'},
        ),
        migrations.AddField(
            model_name='report',
            name='compliance',
            field=models.TextField(blank=True, null=True),
        ),
    ]
